services:
  postgres:
    image: postgres:16-alpine
    container_name: controle-financeiro-postgres
    environment:
      POSTGRES_DB: controle_financeiro
      POSTGRES_USER: controle
      POSTGRES_PASSWORD: controle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
